version: '3.9'
services:
  db:
    image: mysql:8.0.28
    ports:
        - "3307:3307"
    environment:
      MYSQL_USER: root 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taverna_api

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    image: taverna_imagem1
    container_name: taverna_conteiner1
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/taverna_api
    depends_on:
      - db

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: taverna_imagem2
    container_name: taverna_conteiner2
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/taverna_api
    depends_on:
      - db

  spa-app:
    build:
      context: ./taverna-fe
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - app1
      - app2

  nginx:
    image: nginx:latest
    container_name: nginx_conteiner
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2