version: '3.9'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    image: taverna_imagem1
    container_name: taverna_conteiner1
    ports:
      - "8081:8080"

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: taverna_imagem2
    container_name: taverna_conteiner2
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    container_name: nginx_conteiner
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2